version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./app:/work

  web:
    image: nginx:1.20-alpine
    ports:
      - 9090:90
    volumes:
      - ./app:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  # 追記
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "4306:3306"

volumes:
  db-store: null
